services:
  - type: web
    name: project-react
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

